[package]
name = "mancho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
image = "0.25.1"
num-complex = "0.4.6"
rand = "0.8.5"
rustfft = "6.2.0"
